<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('orders')->truncate();
        DB::table('orders')->insert([
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 960000,
                'shipName' => 'Nguyễn Hoàng Đức',
                'shipPhone' => '0837287287',
                'shipAddress' => 'Đối diện Trường Tiểu Học, THCS & THPT Nguyễn Siêu',
                'note' => 'Không có ghi chú',
                'status' => 1,
                'created_at' => '2021-06-02',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 50000,
                'shipName' => 'Nguyễn Tiến Dũng',
                'shipPhone' => '0389776228',
                'shipAddress' => 'Chung Cư HOME City 177 Trung Kính',
                'note' => 'Không có ghi chú',
                'status' => 1,
                'created_at' => '2021-07-22',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 20000,
                'shipName' => 'Phương Hoàng',
                'shipPhone' => '0334670699',
                'shipAddress' => 'Ngõ 173 Trung Kính',
                'note' => 'Không có ghi chú',
                'status' => 1,
                'created_at' => '2021-06-20',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 15000,
                'shipName' => 'Phương Hoàng',
                'shipPhone' => '0837287287',
                'shipAddress' => 'Cổng Trường Đại Học Phương Đông',
                'note' => 'Không có ghi chú',
                'status' => 1,
                'created_at' => '2021-09-02',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 20000,
                'shipName' => 'Nguyễn Công Phượng',
                'shipPhone' => '0312343569',
                'shipAddress' => 'Ngõ 68 Trung Kính',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-02',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 1,
                'totalPrice' => 40000,
                'shipName' => 'Phương Hoàng',
                'shipPhone' => '0334670699',
                'shipAddress' => 'Ngõ 125 Trung Kính',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-12',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 3,
                'totalPrice' => 10000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Văn Phòng Công Chứng Nguyễn Hùng',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-11',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 3,
                'totalPrice' => 45000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Ngõ 68 Trung Kính',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-17',
            ],
            [
                'districtId' => 5,
                'wardId' => 172,
                'userId' => 3,
                'totalPrice' => 70000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Ngân Hàng Ngoại Thương',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-21',
            ],
            [
                'districtId' => 18,
                'wardId' => 526,
                'userId' => 3,
                'totalPrice' => 30000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Ngõ 55 Thiên Đức',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-25',
            ],
            [
                'districtId' => 18,
                'wardId' => 526,
                'userId' => 3,
                'totalPrice' => 120000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Ngõ 53 Thiên Đức',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-25',
            ],
            [
                'districtId' => 18,
                'wardId' => 526,
                'userId' => 3,
                'totalPrice' => 160000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Cy Cổ Phần Tường Đẹp Cộng',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-21',
            ],
            [
                'districtId' => 18,
                'wardId' => 526,
                'userId' => 3,
                'totalPrice' => 110000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0686789999',
                'shipAddress' => 'Ngõ 63 Đ.Hà Huy Tập',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-10',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 3,
                'totalPrice' => 110000,
                'shipName' => 'Tiến Đặng',
                'shipPhone' => '0837287287',
                'shipAddress' => 'UBND Phường Mỹ Đình 1',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-15',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 35000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Ngõ P2 Lê Quang Đạo',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-13',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 40000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Ngõ 1 Vườn Cam',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-18',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 40000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Ngõ 2 Phố Đồng Me',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-04',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 30000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Ngõ 322/95 Mỹ Đình',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-09',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 140000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Đối diện Trường Cao Đẳng Công Nghệ Bách Khoa Hà Nộ...',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-06',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 4,
                'totalPrice' => 1280000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Nhà Hạ 152/322',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-05',
            ],
            [
                'districtId' => 269,
                'wardId' => 9598,
                'userId' => 4,
                'totalPrice' => 310000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Đài Phát Thanh Đông Dương VN1',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-19',
            ],
            [
                'districtId' => 269,
                'wardId' => 9598,
                'userId' => 5,
                'totalPrice' => 30000,
                'shipName' => 'Thắng Phạm',
                'shipPhone' => '0568686800',
                'shipAddress' => 'Làng Lễ Khê',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-13',
            ],
            [
                'districtId' => 2,
                'wardId' => 58,
                'userId' => 5,
                'totalPrice' => 210000,
                'shipName' => 'Vương Hiếu',
                'shipPhone' => '034737389',
                'shipAddress' => 'P. Ngô Quyền',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-28',
            ],
            [
                'districtId' => 2,
                'wardId' => 58,
                'userId' => 5,
                'totalPrice' => 35000,
                'shipName' => 'Vương Hiếu',
                'shipPhone' => '034737389',
                'shipAddress' => 'Cung Thiếu Nhi Hà Nội Phố Lý Thái Tổ',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-28',
            ],
            [
                'districtId' => 3,
                'wardId' => 112,
                'userId' => 5,
                'totalPrice' => 600000,
                'shipName' => 'Vương Hiếu',
                'shipPhone' => '034737389',
                'shipAddress' => 'Ngõ 13 Dốc Tam Đa',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-29',
            ],
            [
                'districtId' => 5,
                'wardId' => 175,
                'userId' => 6,
                'totalPrice' => 270000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Ngõ 83 Trần Duy Hưng',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-19',
            ],
            [
                'districtId' => 4,
                'wardId' => 118,
                'userId' => 6,
                'totalPrice' => 280000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Ngõ 354 Phố Bắc Cầu',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-24',
            ],
            [
                'districtId' => 269,
                'wardId' => 9598,
                'userId' => 6,
                'totalPrice' => 35000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Thôn Lễ Khê',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-14',
            ],
            [
                'districtId' => 20,
                'wardId' => 649,
                'userId' => 6,
                'totalPrice' => 30000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Trường THCS Tả Thanh Oai',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-08',
            ],
            [
                'districtId' => 19,
                'wardId' => 625,
                'userId' => 6,
                'totalPrice' => 3000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Sau bến xe Mỹ Đình',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-03',
            ],
            [
                'districtId' => 4,
                'wardId' => 118,
                'userId' => 6,
                'totalPrice' => 45000,
                'shipName' => 'Sỹ Cảnh',
                'shipPhone' => '0689999999',
                'shipAddress' => 'Ngõ 354 Phố Bắc Cầu',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-02',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 50000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'B15 Lô 5 Đô Thị Định Công Hà Nội',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-05',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 35000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'B15 Lô 5 Đô Thị Định Công Hà Nội',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-06',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 210000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'B15 Lô 5 Đô Thị Định Công Hà Nội',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-03',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 40000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'B15 Lô 5 Đô Thị Định Công Hà Nội',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-01',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 50000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'Nhà May Ngọc Liên',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-06',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 50000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'Sau Trường Cao Đẳng nghề số 17',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-07',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 70000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'Ngõ 36 Trần Điền',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-07',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 50000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'Ngõ 51 Trần Điền',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-18',
            ],
            [
                'districtId' => 8,
                'wardId' => 307,
                'userId' => 7,
                'totalPrice' => 50000,
                'shipName' => 'Lan Phong',
                'shipPhone' => '045678900',
                'shipAddress' => 'Ngõ 210 Lê Trọng Tấn',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-19',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 40000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-06-16',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 210000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-18',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 150000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-22',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 310000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-08',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 320000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-19',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 40000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-07-07',
            ],
            [
                'districtId' => 250,
                'wardId' => 8973,
                'userId' => 8,
                'totalPrice' => 40000,
                'shipName' => 'Nguyễn Dương',
                'shipPhone' => '0345898989',
                'shipAddress' => 'Ngõ 88/54',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-08',
            ],
            [
                'districtId' => 7,
                'wardId' => 241,
                'userId' => 10,
                'totalPrice' => 60000,
                'shipName' => 'Thành Nguyên',
                'shipPhone' => '034578999',
                'shipAddress' => 'Ngõ Yết Kiêu',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-09',
            ],
            [
                'districtId' => 7,
                'wardId' => 241,
                'userId' => 10,
                'totalPrice' => 40000,
                'shipName' => 'Thành Nguyên',
                'shipPhone' => '034578999',
                'shipAddress' => 'Ngõ Yết Kiêu',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-09-10',
            ],
            [
                'districtId' => 7,
                'wardId' => 241,
                'userId' => 10,
                'totalPrice' => 120,
                'shipName' => 'Thành Nguyên',
                'shipPhone' => '034578999',
                'shipAddress' => 'Ngõ Yết Kiêu',
                'note' => 'Không có ghi chú',
                'status' => 1,
              'created_at' => '2021-08-15',
            ],

        ]);
    }
}
